name: DEPLOY DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    name: Deploy para Ambiente Desenvolvimento
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build e testes
        run: mvn clean package

      - name: Deploy simulado em Desenvolvimento
        run: |
          echo "Deploy em Desenvolvimento concluído"