name: Self-Hosted Runner

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    name: Testar runner auto hospedado
    runs-on: self-hosted
    steps:
      - name: Mostrar sistema
        run: uname -a

      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean install

      - name: Instalar software adicional
        run: |
          sudo apt update
          sudo apt install -y tree
