name: VARS E SECRETS
on:
  workflow_dispatch:

jobs:
  show-vars-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Variaveis
        run: |
          echo "APP_MODE = ${{ vars.APP_MODE }}"
          echo "SUPPORT_EMAIL = ${{ vars.SUPPORT_EMAIL }}"

      - name: Autenticacao com Secret
        run: |
          if [ -z "${{ secrets.PROD_TOKEN }}" ]; then
            echo "PROD_TOKEN não definido"
            exit 1
          fi
          echo "Secret PROD_TOKEN definido"